# Generated by Django 4.0.6 on 2022-07-08 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_jobpost_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'userjobposts',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ManyToManyField(through='post.UserJobPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userjobpost',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobpost'),
        ),
        migrations.AddField(
            model_name='userjobpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
